# 仿真感知默认参数。
perception:
  cloud_transform:
    input_topic: /fastnav/lidar/points
    output_topic: /fastnav/perception/cloud_odom
    target_frame: odom

  cloud_filter:
    input_topic: /fastnav/perception/cloud_odom
    output_topic: /fastnav/perception/cloud_filtered
    range_min: 0.2
    range_max: 20.0
    voxel_leaf_size: 0.1
