#!/bin/sh
#
# @name Gazebo x250 Mid360
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=x250_mid360}

param set-default SIM_GZ_EN 1

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

# The SDF rotor centers are $(\pm a,\pm a)$ in Gazebo ENU with $a=0.0884m$.
# PX4 body uses FRD, so the y sign is flipped relative to Gazebo.
param set-default CA_ROTOR0_PX 0.0884
param set-default CA_ROTOR0_PY 0.0884
param set-default CA_ROTOR0_KM 0.05

param set-default CA_ROTOR1_PX -0.0884
param set-default CA_ROTOR1_PY -0.0884
param set-default CA_ROTOR1_KM 0.05

param set-default CA_ROTOR2_PX 0.0884
param set-default CA_ROTOR2_PY -0.0884
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -0.0884
param set-default CA_ROTOR3_PY 0.0884
param set-default CA_ROTOR3_KM -0.05

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 100
param set-default SIM_GZ_EC_MIN2 100
param set-default SIM_GZ_EC_MIN3 100
param set-default SIM_GZ_EC_MIN4 100

param set-default SIM_GZ_EC_MAX1 1100
param set-default SIM_GZ_EC_MAX2 1100
param set-default SIM_GZ_EC_MAX3 1100
param set-default SIM_GZ_EC_MAX4 1100

# Total mass is about 0.765kg and max total thrust is about 12.1N,
# so hover throttle is around $m g / T_{max} = 0.62$.
param set-default MPC_THR_HOVER 0.62
param set-default NAV_DLL_ACT 2
