// Generated by gencpp from file traj_utils/MincoTrajectory.msg
// DO NOT EDIT!


#ifndef TRAJ_UTILS_MESSAGE_MINCOTRAJECTORY_H
#define TRAJ_UTILS_MESSAGE_MINCOTRAJECTORY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace traj_utils
{
template <class ContainerAllocator>
struct MincoTrajectory_
{
  typedef MincoTrajectory_<ContainerAllocator> Type;

  MincoTrajectory_()
    : header()
    , traj_id(0)
    , order(0)
    , start_time()
    , duration()
    , coef_x()
    , coef_y()
    , coef_z()  {
    }
  MincoTrajectory_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , traj_id(0)
    , order(0)
    , start_time()
    , duration(_alloc)
    , coef_x(_alloc)
    , coef_y(_alloc)
    , coef_z(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _traj_id_type;
  _traj_id_type traj_id;

   typedef int32_t _order_type;
  _order_type order;

   typedef ros::Time _start_time_type;
  _start_time_type start_time;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _duration_type;
  _duration_type duration;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _coef_x_type;
  _coef_x_type coef_x;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _coef_y_type;
  _coef_y_type coef_y;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _coef_z_type;
  _coef_z_type coef_z;





  typedef boost::shared_ptr< ::traj_utils::MincoTrajectory_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::traj_utils::MincoTrajectory_<ContainerAllocator> const> ConstPtr;

}; // struct MincoTrajectory_

typedef ::traj_utils::MincoTrajectory_<std::allocator<void> > MincoTrajectory;

typedef boost::shared_ptr< ::traj_utils::MincoTrajectory > MincoTrajectoryPtr;
typedef boost::shared_ptr< ::traj_utils::MincoTrajectory const> MincoTrajectoryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::traj_utils::MincoTrajectory_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::traj_utils::MincoTrajectory_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::traj_utils::MincoTrajectory_<ContainerAllocator1> & lhs, const ::traj_utils::MincoTrajectory_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.traj_id == rhs.traj_id &&
    lhs.order == rhs.order &&
    lhs.start_time == rhs.start_time &&
    lhs.duration == rhs.duration &&
    lhs.coef_x == rhs.coef_x &&
    lhs.coef_y == rhs.coef_y &&
    lhs.coef_z == rhs.coef_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::traj_utils::MincoTrajectory_<ContainerAllocator1> & lhs, const ::traj_utils::MincoTrajectory_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace traj_utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::traj_utils::MincoTrajectory_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::traj_utils::MincoTrajectory_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traj_utils::MincoTrajectory_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traj_utils::MincoTrajectory_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traj_utils::MincoTrajectory_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traj_utils::MincoTrajectory_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::traj_utils::MincoTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "de89d3d619bcfb3593e56bbf412d2768";
  }

  static const char* value(const ::traj_utils::MincoTrajectory_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xde89d3d619bcfb35ULL;
  static const uint64_t static_value2 = 0x93e56bbf412d2768ULL;
};

template<class ContainerAllocator>
struct DataType< ::traj_utils::MincoTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "traj_utils/MincoTrajectory";
  }

  static const char* value(const ::traj_utils::MincoTrajectory_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::traj_utils::MincoTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# FastNav MINCO trajectory message.\n"
"# Planner publishes this message, traj_utils/minco_traj_server samples it into fastnav_msgs/ControlCommand.\n"
"\n"
"std_msgs/Header header\n"
"\n"
"# Monotonic trajectory id generated by planner.\n"
"uint32 traj_id\n"
"\n"
"# Polynomial order. FastNav currently uses GCOPTER Trajectory<5>, so order should be 5.\n"
"int32 order\n"
"\n"
"# Trajectory start time in the planner frame.\n"
"time start_time\n"
"\n"
"# Piece durations. For $N$ pieces, duration has length $N$.\n"
"float64[] duration\n"
"\n"
"# Per-axis coefficients of each piece.\n"
"# For order 5, each piece owns 6 coefficients. Coefficients are stored in the same order as GCOPTER Piece<5>::CoefficientMat columns.\n"
"# That is, coeff_x[i * 6 + k] is the x-axis coefficient at column $k$ of piece $i$.\n"
"float64[] coef_x\n"
"float64[] coef_y\n"
"float64[] coef_z\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::traj_utils::MincoTrajectory_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::traj_utils::MincoTrajectory_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.traj_id);
      stream.next(m.order);
      stream.next(m.start_time);
      stream.next(m.duration);
      stream.next(m.coef_x);
      stream.next(m.coef_y);
      stream.next(m.coef_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MincoTrajectory_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::traj_utils::MincoTrajectory_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::traj_utils::MincoTrajectory_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "traj_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.traj_id);
    s << indent << "order: ";
    Printer<int32_t>::stream(s, indent + "  ", v.order);
    s << indent << "start_time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.start_time);
    s << indent << "duration[]" << std::endl;
    for (size_t i = 0; i < v.duration.size(); ++i)
    {
      s << indent << "  duration[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.duration[i]);
    }
    s << indent << "coef_x[]" << std::endl;
    for (size_t i = 0; i < v.coef_x.size(); ++i)
    {
      s << indent << "  coef_x[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.coef_x[i]);
    }
    s << indent << "coef_y[]" << std::endl;
    for (size_t i = 0; i < v.coef_y.size(); ++i)
    {
      s << indent << "  coef_y[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.coef_y[i]);
    }
    s << indent << "coef_z[]" << std::endl;
    for (size_t i = 0; i < v.coef_z.size(); ++i)
    {
      s << indent << "  coef_z[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.coef_z[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRAJ_UTILS_MESSAGE_MINCOTRAJECTORY_H
