# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from fastnav_msgs/ObstacleInfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class ObstacleInfo(genpy.Message):
  _md5sum = "25281cdc1a810d2ecef8ab29564e1d71"
  _type = "fastnav_msgs/ObstacleInfo"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# FastNav obstacle information.
# This message is published by fastnav_perception
# and consumed by fastnav_planner.

std_msgs/Header header

bool has_obstacle

float64 min_distance
float64 front_distance
float64 left_distance
float64 right_distance
float64 rear_distance

geometry_msgs/Point nearest_point

uint32 obstacle_point_count
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['header','has_obstacle','min_distance','front_distance','left_distance','right_distance','rear_distance','nearest_point','obstacle_point_count']
  _slot_types = ['std_msgs/Header','bool','float64','float64','float64','float64','float64','geometry_msgs/Point','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,has_obstacle,min_distance,front_distance,left_distance,right_distance,rear_distance,nearest_point,obstacle_point_count

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ObstacleInfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.has_obstacle is None:
        self.has_obstacle = False
      if self.min_distance is None:
        self.min_distance = 0.
      if self.front_distance is None:
        self.front_distance = 0.
      if self.left_distance is None:
        self.left_distance = 0.
      if self.right_distance is None:
        self.right_distance = 0.
      if self.rear_distance is None:
        self.rear_distance = 0.
      if self.nearest_point is None:
        self.nearest_point = geometry_msgs.msg.Point()
      if self.obstacle_point_count is None:
        self.obstacle_point_count = 0
    else:
      self.header = std_msgs.msg.Header()
      self.has_obstacle = False
      self.min_distance = 0.
      self.front_distance = 0.
      self.left_distance = 0.
      self.right_distance = 0.
      self.rear_distance = 0.
      self.nearest_point = geometry_msgs.msg.Point()
      self.obstacle_point_count = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B8dI().pack(_x.has_obstacle, _x.min_distance, _x.front_distance, _x.left_distance, _x.right_distance, _x.rear_distance, _x.nearest_point.x, _x.nearest_point.y, _x.nearest_point.z, _x.obstacle_point_count))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.nearest_point is None:
        self.nearest_point = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 69
      (_x.has_obstacle, _x.min_distance, _x.front_distance, _x.left_distance, _x.right_distance, _x.rear_distance, _x.nearest_point.x, _x.nearest_point.y, _x.nearest_point.z, _x.obstacle_point_count,) = _get_struct_B8dI().unpack(str[start:end])
      self.has_obstacle = bool(self.has_obstacle)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B8dI().pack(_x.has_obstacle, _x.min_distance, _x.front_distance, _x.left_distance, _x.right_distance, _x.rear_distance, _x.nearest_point.x, _x.nearest_point.y, _x.nearest_point.z, _x.obstacle_point_count))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.nearest_point is None:
        self.nearest_point = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 69
      (_x.has_obstacle, _x.min_distance, _x.front_distance, _x.left_distance, _x.right_distance, _x.rear_distance, _x.nearest_point.x, _x.nearest_point.y, _x.nearest_point.z, _x.obstacle_point_count,) = _get_struct_B8dI().unpack(str[start:end])
      self.has_obstacle = bool(self.has_obstacle)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_B8dI = None
def _get_struct_B8dI():
    global _struct_B8dI
    if _struct_B8dI is None:
        _struct_B8dI = struct.Struct("<B8dI")
    return _struct_B8dI
