# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from fastnav_msgs/PlannerState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class PlannerState(genpy.Message):
  _md5sum = "2f756c3d9a0a66ce8958743e6cc2f690"
  _type = "fastnav_msgs/PlannerState"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# FastNav planner state.
# This message is published by fastnav_planner
# for debugging and visualization.

std_msgs/Header header

uint8 STATE_IDLE        = 0
uint8 STATE_TAKEOFF     = 1
uint8 STATE_NAVIGATE    = 2
uint8 STATE_AVOID       = 3
uint8 STATE_HOVER       = 4
uint8 STATE_GOAL_REACHED = 5
uint8 STATE_EMERGENCY   = 6

uint8 state
string state_name

geometry_msgs/Point current_goal

bool goal_reached
bool has_obstacle
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  # Pseudo-constants
  STATE_IDLE = 0
  STATE_TAKEOFF = 1
  STATE_NAVIGATE = 2
  STATE_AVOID = 3
  STATE_HOVER = 4
  STATE_GOAL_REACHED = 5
  STATE_EMERGENCY = 6

  __slots__ = ['header','state','state_name','current_goal','goal_reached','has_obstacle']
  _slot_types = ['std_msgs/Header','uint8','string','geometry_msgs/Point','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,state,state_name,current_goal,goal_reached,has_obstacle

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PlannerState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.state is None:
        self.state = 0
      if self.state_name is None:
        self.state_name = ''
      if self.current_goal is None:
        self.current_goal = geometry_msgs.msg.Point()
      if self.goal_reached is None:
        self.goal_reached = False
      if self.has_obstacle is None:
        self.has_obstacle = False
    else:
      self.header = std_msgs.msg.Header()
      self.state = 0
      self.state_name = ''
      self.current_goal = geometry_msgs.msg.Point()
      self.goal_reached = False
      self.has_obstacle = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.state
      buff.write(_get_struct_B().pack(_x))
      _x = self.state_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3d2B().pack(_x.current_goal.x, _x.current_goal.y, _x.current_goal.z, _x.goal_reached, _x.has_obstacle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.current_goal is None:
        self.current_goal = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 1
      (self.state,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.state_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.state_name = str[start:end]
      _x = self
      start = end
      end += 26
      (_x.current_goal.x, _x.current_goal.y, _x.current_goal.z, _x.goal_reached, _x.has_obstacle,) = _get_struct_3d2B().unpack(str[start:end])
      self.goal_reached = bool(self.goal_reached)
      self.has_obstacle = bool(self.has_obstacle)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.state
      buff.write(_get_struct_B().pack(_x))
      _x = self.state_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3d2B().pack(_x.current_goal.x, _x.current_goal.y, _x.current_goal.z, _x.goal_reached, _x.has_obstacle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.current_goal is None:
        self.current_goal = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 1
      (self.state,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.state_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.state_name = str[start:end]
      _x = self
      start = end
      end += 26
      (_x.current_goal.x, _x.current_goal.y, _x.current_goal.z, _x.goal_reached, _x.has_obstacle,) = _get_struct_3d2B().unpack(str[start:end])
      self.goal_reached = bool(self.goal_reached)
      self.has_obstacle = bool(self.has_obstacle)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d2B = None
def _get_struct_3d2B():
    global _struct_3d2B
    if _struct_3d2B is None:
        _struct_3d2B = struct.Struct("<3d2B")
    return _struct_3d2B
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
