// Generated by gencpp from file fastnav_msgs/ControlCommand.msg
// DO NOT EDIT!


#ifndef FASTNAV_MSGS_MESSAGE_CONTROLCOMMAND_H
#define FASTNAV_MSGS_MESSAGE_CONTROLCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace fastnav_msgs
{
template <class ContainerAllocator>
struct ControlCommand_
{
  typedef ControlCommand_<ContainerAllocator> Type;

  ControlCommand_()
    : header()
    , command_type(0)
    , trajectory_id(0)
    , position()
    , velocity()
    , acceleration()
    , jerk()
    , yaw(0.0)
    , yaw_rate(0.0)
    , enable(false)  {
    }
  ControlCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , command_type(0)
    , trajectory_id(0)
    , position(_alloc)
    , velocity(_alloc)
    , acceleration(_alloc)
    , jerk(_alloc)
    , yaw(0.0)
    , yaw_rate(0.0)
    , enable(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _command_type_type;
  _command_type_type command_type;

   typedef uint32_t _trajectory_id_type;
  _trajectory_id_type trajectory_id;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _acceleration_type;
  _acceleration_type acceleration;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _jerk_type;
  _jerk_type jerk;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef double _yaw_rate_type;
  _yaw_rate_type yaw_rate;

   typedef uint8_t _enable_type;
  _enable_type enable;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(COMMAND_POSITION)
  #undef COMMAND_POSITION
#endif
#if defined(_WIN32) && defined(COMMAND_VELOCITY)
  #undef COMMAND_VELOCITY
#endif
#if defined(_WIN32) && defined(COMMAND_HOVER)
  #undef COMMAND_HOVER
#endif
#if defined(_WIN32) && defined(COMMAND_LAND)
  #undef COMMAND_LAND
#endif
#if defined(_WIN32) && defined(COMMAND_IDLE)
  #undef COMMAND_IDLE
#endif
#if defined(_WIN32) && defined(COMMAND_TRAJECTORY)
  #undef COMMAND_TRAJECTORY
#endif

  enum {
    COMMAND_POSITION = 0u,
    COMMAND_VELOCITY = 1u,
    COMMAND_HOVER = 2u,
    COMMAND_LAND = 3u,
    COMMAND_IDLE = 4u,
    COMMAND_TRAJECTORY = 5u,
  };


  typedef boost::shared_ptr< ::fastnav_msgs::ControlCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fastnav_msgs::ControlCommand_<ContainerAllocator> const> ConstPtr;

}; // struct ControlCommand_

typedef ::fastnav_msgs::ControlCommand_<std::allocator<void> > ControlCommand;

typedef boost::shared_ptr< ::fastnav_msgs::ControlCommand > ControlCommandPtr;
typedef boost::shared_ptr< ::fastnav_msgs::ControlCommand const> ControlCommandConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fastnav_msgs::ControlCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fastnav_msgs::ControlCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fastnav_msgs::ControlCommand_<ContainerAllocator1> & lhs, const ::fastnav_msgs::ControlCommand_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.command_type == rhs.command_type &&
    lhs.trajectory_id == rhs.trajectory_id &&
    lhs.position == rhs.position &&
    lhs.velocity == rhs.velocity &&
    lhs.acceleration == rhs.acceleration &&
    lhs.jerk == rhs.jerk &&
    lhs.yaw == rhs.yaw &&
    lhs.yaw_rate == rhs.yaw_rate &&
    lhs.enable == rhs.enable;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fastnav_msgs::ControlCommand_<ContainerAllocator1> & lhs, const ::fastnav_msgs::ControlCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fastnav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fastnav_msgs::ControlCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fastnav_msgs::ControlCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fastnav_msgs::ControlCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fastnav_msgs::ControlCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fastnav_msgs::ControlCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fastnav_msgs::ControlCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fastnav_msgs::ControlCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0fd67f68d7beec39a04c5cf43f0fca02";
  }

  static const char* value(const ::fastnav_msgs::ControlCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0fd67f68d7beec39ULL;
  static const uint64_t static_value2 = 0xa04c5cf43f0fca02ULL;
};

template<class ContainerAllocator>
struct DataType< ::fastnav_msgs::ControlCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fastnav_msgs/ControlCommand";
  }

  static const char* value(const ::fastnav_msgs::ControlCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fastnav_msgs::ControlCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# FastNav internal control command.\n"
"# This message is usually published by traj_utils/minco_traj_server\n"
"# and consumed by fastnav_control. Planner should publish trajectory, not direct PX4 setpoint.\n"
"\n"
"std_msgs/Header header\n"
"\n"
"# Command type\n"
"uint8 COMMAND_POSITION = 0\n"
"uint8 COMMAND_VELOCITY = 1\n"
"uint8 COMMAND_HOVER    = 2\n"
"uint8 COMMAND_LAND     = 3\n"
"uint8 COMMAND_IDLE     = 4\n"
"uint8 COMMAND_TRAJECTORY = 5\n"
"\n"
"uint8 command_type\n"
"\n"
"# Trajectory id, used to reject stale sampled commands if needed.\n"
"uint32 trajectory_id\n"
"\n"
"# Position setpoint in local frame\n"
"geometry_msgs/Point position\n"
"\n"
"# Velocity setpoint in local frame\n"
"geometry_msgs/Vector3 velocity\n"
"\n"
"# Acceleration feed-forward in local frame, sampled from $a(t)$.\n"
"geometry_msgs/Vector3 acceleration\n"
"\n"
"# Jerk feed-forward in local frame, sampled from $j(t)$; current PX4 raw local setpoint does not consume jerk directly.\n"
"geometry_msgs/Vector3 jerk\n"
"\n"
"# Yaw angle for position control\n"
"float64 yaw\n"
"\n"
"# Yaw rate for velocity control\n"
"float64 yaw_rate\n"
"\n"
"# Whether this command is valid\n"
"bool enable\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::fastnav_msgs::ControlCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fastnav_msgs::ControlCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.command_type);
      stream.next(m.trajectory_id);
      stream.next(m.position);
      stream.next(m.velocity);
      stream.next(m.acceleration);
      stream.next(m.jerk);
      stream.next(m.yaw);
      stream.next(m.yaw_rate);
      stream.next(m.enable);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fastnav_msgs::ControlCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fastnav_msgs::ControlCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "command_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.command_type);
    s << indent << "trajectory_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.trajectory_id);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "velocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
    s << indent << "acceleration: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.acceleration);
    s << indent << "jerk: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.jerk);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "yaw_rate: ";
    Printer<double>::stream(s, indent + "  ", v.yaw_rate);
    s << indent << "enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FASTNAV_MSGS_MESSAGE_CONTROLCOMMAND_H
