// Generated by gencpp from file fastnav_msgs/ObstacleInfo.msg
// DO NOT EDIT!


#ifndef FASTNAV_MSGS_MESSAGE_OBSTACLEINFO_H
#define FASTNAV_MSGS_MESSAGE_OBSTACLEINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>

namespace fastnav_msgs
{
template <class ContainerAllocator>
struct ObstacleInfo_
{
  typedef ObstacleInfo_<ContainerAllocator> Type;

  ObstacleInfo_()
    : header()
    , has_obstacle(false)
    , min_distance(0.0)
    , front_distance(0.0)
    , left_distance(0.0)
    , right_distance(0.0)
    , rear_distance(0.0)
    , nearest_point()
    , obstacle_point_count(0)  {
    }
  ObstacleInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , has_obstacle(false)
    , min_distance(0.0)
    , front_distance(0.0)
    , left_distance(0.0)
    , right_distance(0.0)
    , rear_distance(0.0)
    , nearest_point(_alloc)
    , obstacle_point_count(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _has_obstacle_type;
  _has_obstacle_type has_obstacle;

   typedef double _min_distance_type;
  _min_distance_type min_distance;

   typedef double _front_distance_type;
  _front_distance_type front_distance;

   typedef double _left_distance_type;
  _left_distance_type left_distance;

   typedef double _right_distance_type;
  _right_distance_type right_distance;

   typedef double _rear_distance_type;
  _rear_distance_type rear_distance;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _nearest_point_type;
  _nearest_point_type nearest_point;

   typedef uint32_t _obstacle_point_count_type;
  _obstacle_point_count_type obstacle_point_count;





  typedef boost::shared_ptr< ::fastnav_msgs::ObstacleInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fastnav_msgs::ObstacleInfo_<ContainerAllocator> const> ConstPtr;

}; // struct ObstacleInfo_

typedef ::fastnav_msgs::ObstacleInfo_<std::allocator<void> > ObstacleInfo;

typedef boost::shared_ptr< ::fastnav_msgs::ObstacleInfo > ObstacleInfoPtr;
typedef boost::shared_ptr< ::fastnav_msgs::ObstacleInfo const> ObstacleInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fastnav_msgs::ObstacleInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fastnav_msgs::ObstacleInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fastnav_msgs::ObstacleInfo_<ContainerAllocator1> & lhs, const ::fastnav_msgs::ObstacleInfo_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.has_obstacle == rhs.has_obstacle &&
    lhs.min_distance == rhs.min_distance &&
    lhs.front_distance == rhs.front_distance &&
    lhs.left_distance == rhs.left_distance &&
    lhs.right_distance == rhs.right_distance &&
    lhs.rear_distance == rhs.rear_distance &&
    lhs.nearest_point == rhs.nearest_point &&
    lhs.obstacle_point_count == rhs.obstacle_point_count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fastnav_msgs::ObstacleInfo_<ContainerAllocator1> & lhs, const ::fastnav_msgs::ObstacleInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fastnav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fastnav_msgs::ObstacleInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fastnav_msgs::ObstacleInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fastnav_msgs::ObstacleInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fastnav_msgs::ObstacleInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fastnav_msgs::ObstacleInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fastnav_msgs::ObstacleInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fastnav_msgs::ObstacleInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25281cdc1a810d2ecef8ab29564e1d71";
  }

  static const char* value(const ::fastnav_msgs::ObstacleInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25281cdc1a810d2eULL;
  static const uint64_t static_value2 = 0xcef8ab29564e1d71ULL;
};

template<class ContainerAllocator>
struct DataType< ::fastnav_msgs::ObstacleInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fastnav_msgs/ObstacleInfo";
  }

  static const char* value(const ::fastnav_msgs::ObstacleInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fastnav_msgs::ObstacleInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# FastNav obstacle information.\n"
"# This message is published by fastnav_perception\n"
"# and consumed by fastnav_planner.\n"
"\n"
"std_msgs/Header header\n"
"\n"
"bool has_obstacle\n"
"\n"
"float64 min_distance\n"
"float64 front_distance\n"
"float64 left_distance\n"
"float64 right_distance\n"
"float64 rear_distance\n"
"\n"
"geometry_msgs/Point nearest_point\n"
"\n"
"uint32 obstacle_point_count\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::fastnav_msgs::ObstacleInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fastnav_msgs::ObstacleInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.has_obstacle);
      stream.next(m.min_distance);
      stream.next(m.front_distance);
      stream.next(m.left_distance);
      stream.next(m.right_distance);
      stream.next(m.rear_distance);
      stream.next(m.nearest_point);
      stream.next(m.obstacle_point_count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstacleInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fastnav_msgs::ObstacleInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fastnav_msgs::ObstacleInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "has_obstacle: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.has_obstacle);
    s << indent << "min_distance: ";
    Printer<double>::stream(s, indent + "  ", v.min_distance);
    s << indent << "front_distance: ";
    Printer<double>::stream(s, indent + "  ", v.front_distance);
    s << indent << "left_distance: ";
    Printer<double>::stream(s, indent + "  ", v.left_distance);
    s << indent << "right_distance: ";
    Printer<double>::stream(s, indent + "  ", v.right_distance);
    s << indent << "rear_distance: ";
    Printer<double>::stream(s, indent + "  ", v.rear_distance);
    s << indent << "nearest_point: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.nearest_point);
    s << indent << "obstacle_point_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.obstacle_point_count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FASTNAV_MSGS_MESSAGE_OBSTACLEINFO_H
