// Generated by gencpp from file fastnav_msgs/PlannerState.msg
// DO NOT EDIT!


#ifndef FASTNAV_MSGS_MESSAGE_PLANNERSTATE_H
#define FASTNAV_MSGS_MESSAGE_PLANNERSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>

namespace fastnav_msgs
{
template <class ContainerAllocator>
struct PlannerState_
{
  typedef PlannerState_<ContainerAllocator> Type;

  PlannerState_()
    : header()
    , state(0)
    , state_name()
    , current_goal()
    , goal_reached(false)
    , has_obstacle(false)  {
    }
  PlannerState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , state(0)
    , state_name(_alloc)
    , current_goal(_alloc)
    , goal_reached(false)
    , has_obstacle(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _state_type;
  _state_type state;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _state_name_type;
  _state_name_type state_name;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _current_goal_type;
  _current_goal_type current_goal;

   typedef uint8_t _goal_reached_type;
  _goal_reached_type goal_reached;

   typedef uint8_t _has_obstacle_type;
  _has_obstacle_type has_obstacle;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(STATE_IDLE)
  #undef STATE_IDLE
#endif
#if defined(_WIN32) && defined(STATE_TAKEOFF)
  #undef STATE_TAKEOFF
#endif
#if defined(_WIN32) && defined(STATE_NAVIGATE)
  #undef STATE_NAVIGATE
#endif
#if defined(_WIN32) && defined(STATE_AVOID)
  #undef STATE_AVOID
#endif
#if defined(_WIN32) && defined(STATE_HOVER)
  #undef STATE_HOVER
#endif
#if defined(_WIN32) && defined(STATE_GOAL_REACHED)
  #undef STATE_GOAL_REACHED
#endif
#if defined(_WIN32) && defined(STATE_EMERGENCY)
  #undef STATE_EMERGENCY
#endif

  enum {
    STATE_IDLE = 0u,
    STATE_TAKEOFF = 1u,
    STATE_NAVIGATE = 2u,
    STATE_AVOID = 3u,
    STATE_HOVER = 4u,
    STATE_GOAL_REACHED = 5u,
    STATE_EMERGENCY = 6u,
  };


  typedef boost::shared_ptr< ::fastnav_msgs::PlannerState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fastnav_msgs::PlannerState_<ContainerAllocator> const> ConstPtr;

}; // struct PlannerState_

typedef ::fastnav_msgs::PlannerState_<std::allocator<void> > PlannerState;

typedef boost::shared_ptr< ::fastnav_msgs::PlannerState > PlannerStatePtr;
typedef boost::shared_ptr< ::fastnav_msgs::PlannerState const> PlannerStateConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fastnav_msgs::PlannerState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fastnav_msgs::PlannerState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fastnav_msgs::PlannerState_<ContainerAllocator1> & lhs, const ::fastnav_msgs::PlannerState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.state == rhs.state &&
    lhs.state_name == rhs.state_name &&
    lhs.current_goal == rhs.current_goal &&
    lhs.goal_reached == rhs.goal_reached &&
    lhs.has_obstacle == rhs.has_obstacle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fastnav_msgs::PlannerState_<ContainerAllocator1> & lhs, const ::fastnav_msgs::PlannerState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fastnav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fastnav_msgs::PlannerState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fastnav_msgs::PlannerState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fastnav_msgs::PlannerState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fastnav_msgs::PlannerState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fastnav_msgs::PlannerState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fastnav_msgs::PlannerState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fastnav_msgs::PlannerState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2f756c3d9a0a66ce8958743e6cc2f690";
  }

  static const char* value(const ::fastnav_msgs::PlannerState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2f756c3d9a0a66ceULL;
  static const uint64_t static_value2 = 0x8958743e6cc2f690ULL;
};

template<class ContainerAllocator>
struct DataType< ::fastnav_msgs::PlannerState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fastnav_msgs/PlannerState";
  }

  static const char* value(const ::fastnav_msgs::PlannerState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fastnav_msgs::PlannerState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# FastNav planner state.\n"
"# This message is published by fastnav_planner\n"
"# for debugging and visualization.\n"
"\n"
"std_msgs/Header header\n"
"\n"
"uint8 STATE_IDLE        = 0\n"
"uint8 STATE_TAKEOFF     = 1\n"
"uint8 STATE_NAVIGATE    = 2\n"
"uint8 STATE_AVOID       = 3\n"
"uint8 STATE_HOVER       = 4\n"
"uint8 STATE_GOAL_REACHED = 5\n"
"uint8 STATE_EMERGENCY   = 6\n"
"\n"
"uint8 state\n"
"string state_name\n"
"\n"
"geometry_msgs/Point current_goal\n"
"\n"
"bool goal_reached\n"
"bool has_obstacle\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::fastnav_msgs::PlannerState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fastnav_msgs::PlannerState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.state);
      stream.next(m.state_name);
      stream.next(m.current_goal);
      stream.next(m.goal_reached);
      stream.next(m.has_obstacle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlannerState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fastnav_msgs::PlannerState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fastnav_msgs::PlannerState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
    s << indent << "state_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.state_name);
    s << indent << "current_goal: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.current_goal);
    s << indent << "goal_reached: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.goal_reached);
    s << indent << "has_obstacle: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.has_obstacle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FASTNAV_MSGS_MESSAGE_PLANNERSTATE_H
